def get_field_types():
    return [
        {'id': 'address', 'desc': 'Full Address', 'example': 'To do', 'script': '', 'resolved_functions':[]},
        {'id': 'city', 'desc': 'Random City', 'example': 'To do', 'script': '', 'resolved_functions':[]},
        {'id': 'latitude', 'desc': 'Latitude', 'example': 'To do', 'script': '', 'resolved_functions':[]},
        {'id': 'longitude', 'desc': 'Longitude', 'example': 'To do', 'script': '', 'resolved_functions':[]},
        {'id': 'postal_code', 'desc': 'Postal Code', 'example': 'To do', 'script': '', 'resolved_functions':[]},
        {'id': 'company', 'desc': 'Company name', 'example': 'To do', 'script': '', 'resolved_functions':[]},
        {'id': 'day_of_week', 'desc': 'Day of Week Name', 'example': 'To do', 'script': '', 'resolved_functions':[]},
        {'id': 'timestamp', 'desc': 'Unix Timestamp', 'example': 'To do', 'script': '', 'resolved_functions':[]},
        {'id': 'dish', 'desc': 'Dish Name', 'example': 'To do', 'script': '', 'resolved_functions':[]},
        {'id': 'drink', 'desc': 'Drink Name', 'example': 'To do', 'script': '', 'resolved_functions':[]},
        {'id': 'fruit', 'desc': 'Fruit name', 'example': 'To do', 'script': '', 'resolved_functions':[]},
        {'id': 'vegetable', 'desc': 'Vegetable Name', 'example': 'To do', 'script': '', 'resolved_functions':[]},
        {'id': 'email', 'desc': 'Email Address', 'example': 'To do', 'script': '', 'resolved_functions':[]},
        {'id': 'full_name', 'desc': 'Person`s full name', 'example': 'To do', 'script': '', 'resolved_functions':[]},
        {'id': 'job', 'desc': 'Job title', 'example': 'To do', 'script': '', 'resolved_functions':[]},
        {'id': 'phone', 'desc': 'Phone number', 'example': 'To do', 'script': '', 'resolved_functions':[]},
        {'id': 'username', 'desc': 'User name', 'example': 'To do', 'script': '', 'resolved_functions':[]},
        {'id': 'text', 'desc': 'Random text', 'example': 'To do', 'script': '', 'resolved_functions':[]},
        {'id': 'title', 'desc': 'Title', 'example': 'To do', 'script': '', 'resolved_functions':[]},
        {'id': 'uuid', 'desc': 'UUID 4', 'example': 'To do', 'script': '', 'resolved_functions':[]},
        {'id': 'file_name', 'desc': 'File name', 'example': 'To do', 'script': '', 'resolved_functions': []},
        {'id': 'url_home', 'desc': 'Site url', 'example': 'To do', 'script': '', 'resolved_functions': []},
        {'id': 'mac', 'desc': 'Mac Address', 'example': 'To do', 'script': '', 'resolved_functions': []},
        {'id': 'ip', 'desc': 'IP Address', 'example': 'To do', 'script': '', 'resolved_functions': []},
        {'id': 'car_model', 'desc': 'Car model', 'example': 'To do', 'script': '', 'resolved_functions': []},
        {'id': 'sequence', 'desc': 'Digit Sequence', 'example': '10, 20, 30 ...', 'script': 'start = 1; step = 1',
         'resolved_functions': []},
        {'id': 'price', 'desc': 'Price', 'example': '10.06, 11.2 ...', 'script': 'min = 1; max = 100',
         'resolved_functions': []},
        {'id': 'datetime', 'desc': 'Date and time', 'example': '01.09.2019 21:29:20',
         'script': 'min = 2018; max = 2019; format= %d%m%Y %h:%m:%s', 'resolved_functions': []},
        {'id': 'date', 'desc': 'Date and time', 'example': '01.09.2010',
         'script': 'min = 2018; max = 2019; format= %d%m%Y', 'resolved_functions': []},
        {'id': 'ean_code', 'desc': 'EAN Code', 'example': '4002232323231',
         'script': 'type = ean-13', 'resolved_functions': []},
        {'id': 'int', 'desc': 'Integer numbers', 'example': '103, 200, 423',
         'script': 'min = 10; max = 104; ', 'resolved_functions': []},
        {'id': 'float', 'desc': 'Float numbers', 'example': '1.04, 2.05 ...',
         'script': 'min = 10; max = 104; ', 'resolved_functions': []},




    ]